spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/resturant_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true # Set to true to see SQL queries in console
    properties:
      hibernate:
        format_sql: true # Format SQL queries in console

server:
  port: 8080 # Set your desired port number

