package itep.resturant.service.entity;

public enum Permission {
    READ_ALL_CUISINE,
    SAVE_ONE_CUISINE,
    DELETE_ONE_CUISINE,
    UPDATE_ONE_CUISINE,
    READ_ALL_MENU,
    SAVE_ONE_MENU,
    DELETE_ONE_MENU,
    UPDATE_ONE_MENU,
    READ_ALL_ITEM,
    SAVE_ONE_ITEM,
    DELETE_ONE_ITEM,
    UPDATE_ONE_ITEM,
    READ_ALL_RESTAURANT,
    SAVE_ONE_RESTAURANT,
    DELETE_ONE_RESTAURANT,
    UPDATE_ONE_RESTAURANT
}
