#name: Build and Push Docker Image
#
#on:
#  push:
#    branches:
#      - develop
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    permissions:
#        contents: read
#        packages: write
#
#    steps:
#          - uses: actions/checkout@v3
#          - name: Set up JDK 11
#            uses: actions/setup-java@v3
#            with:
#              java-version: '17'
#              distribution: 'temurin'
#              server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
#              settings-path: ${{ github.workspace }} # location for the settings.xml file
#
#          - name: Build Docker image
#            run: |
#             docker build -t alshaibi3/itep .
#             docker tag alshaibi3/itep alshaibi3/itep:latest
#
#          - name: Log in to Docker Hub
#            uses: docker/login-action@v1
#            with:
#              username: ${{ secrets.DOCKER_USERNAME }}
#              password: ${{ secrets.DOCKER_PASSWORD }}
#
#          - name: Push Docker image to Docker Hub
#            run: |
#             docker push alshaibi3/itep:latest


name: build and deploy spring-api
on:
    push:
      branches:
        - develop

jobs:
    build-deploy:
      name: build and deploy spring-api
      runs-on: ubuntu-20.04
      steps:
        - name: checkout code
          uses: actions/checkout@v3

        - name: setup jdk 17
          uses: actions/setup-java@v3
          with:
            distribution: 'corretto'
            java-version: 17

#        - name: unit tests
#          run: mvn -B test --file pom.xml

        - name: build the app
          run: |
            mvn clean
            mvn -B package --file pom.xml
        - name: build the docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            dockerfile: Dockerfile
            push: false
            tags: ${{ secrets.DOCKER_USERNAME }}/itep:latest

        - name: login to docker hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: push the docker image to docker hub
          uses: docker/build-push-action@v4
          with:
            context: .
            dockerfile: Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/itep:latest
